### ISSUE TITLE
I dont know how create an embed for the suscriptions

### ISSUE THREAD

**Issue by scuffitotw** [cFyt/twitch-log-to-discord#1]
Hello, i put this repository on my bot and idk how to create an embed for the suscriptions.

**Comment by cFyt** [comment]
see this https://discordjs.guide/popular-topics/embeds.html

**Comment by scuffitotw** [comment]
yeah, but idk where put this code in the embed "othch.send(`**${userstate['display-name']}** has just subscribed to ${channel.slice(1)}!`)

**Comment by cFyt** [comment]
const exampleEmbed = new MessageEmbed()
	.setColor('#0099ff')
	.setTitle('Some title')
	.setDescription('**'+userstate['display-name']+'** has just subscribed to '+channel.slice(1)+'!')
	.setTimestamp()
	.setFooter('Some footer text here', 'https://i.imgur.com/wSTFkRM.png');

othch.send(exampleEmbed);

**Comment by scuffitotw** [comment]
Thx, and i have other dought this text how can i put "${username}, gifted subscriptions to ${recipient}"

**Comment by cFyt** [comment]
write this between `

**Comment by scuffitotw** [comment]
This? +['username']+'

**Comment by cFyt** [comment]
if you want add username in text write ${username} between `

**Comment by scuffitotw** [comment]
Okey thx =)
